# Generated by Django 4.2.5 on 2023-09-09 15:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("japanese_name", models.CharField(max_length=255)),
                ("pokedex_number", models.IntegerField()),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("height_m", models.FloatField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("hp", models.IntegerField()),
                ("sp_attack", models.IntegerField()),
                ("sp_defense", models.IntegerField()),
                ("speed", models.IntegerField()),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("generation", models.IntegerField()),
                ("is_legendary", models.BooleanField()),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pokedex.classification",
                    ),
                ),
            ],
        ),
    ]
